name: Testing Matrix

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_all_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
          - os: macos-14
            xcode: 15.4
            platform: "iOS Simulator,name=iPhone 15 Pro,OS=17.5"
          - os: macos-14
            xcode: 15.4
            platform: "macOS"
          - os: macos-14
            xcode: 15.4
            platform: "macOS,variant=Mac Catalyst"
          - os: macos-14
            xcode: 15.4
            platform: "visionOS Simulator,name=Apple Vision Pro,OS=1.2"
          - os: macos-14
            xcode: 15.4
            platform: "tvOS Simulator,name=Apple TV,OS=17.5"

          # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
          - os: macos-15
            xcode: 16.4
            platform: "iOS Simulator,name=iPhone 16 Pro,OS=18.5"
          - os: macos-15
            xcode: 16.4
            platform: "macOS"
          - os: macos-15
            xcode: 16.4
            platform: "macOS,variant=Mac Catalyst"
          - os: macos-15
            xcode: 16.4
            platform: "visionOS Simulator,name=Apple Vision Pro,OS=2.5"
          - os: macos-15
            xcode: 16.4
            platform: "tvOS Simulator,name=Apple TV,OS=18.5"

          # https://github.com/actions/runner-images/tree/main/images/macos
          # - os: macos-15
          #   xcode: latest
          #   platform: "iOS Simulator,name=iPhone 16 Pro,OS=26.0"
          - os: macos-15
            xcode: latest
            platform: "macOS"
          # - os: macos-15
          #   xcode: latest
          #   platform: "macOS,variant=Mac Catalyst"
          # - os: macos-15
          #   xcode: latest
          #   platform: "visionOS Simulator,name=Apple Vision Pro,OS=26.0"
          # - os: macos-15
          #   xcode: latest
          #   platform: "tvOS Simulator,name=Apple TV,OS=26.0"

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Xcode Version
        run: xcodebuild -version

      - name: Show SDKs
        run: xcodebuild -showsdks

      - name: Show Destinations
        run: xcodebuild -scheme LiveKitComponents -showdestinations

      - name: Run Tests on ${{ matrix.platform }}
        run: xcodebuild test -scheme LiveKitComponents -destination 'platform=${{ matrix.platform }}' -parallel-testing-enabled YES
