name: Testing Matrix

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_all_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
          - os: macos-13
            xcode: 14.2
            platform: "iOS Simulator,OS=17.2,name=iPhone 14 Pro"
          - os: macos-13
            xcode: 14.2
            platform: "macOS"
          - os: macos-13
            xcode: 14.2
            platform: "macOS,variant=Mac Catalyst"
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
          - os: macos-14
            xcode: 15.4
            platform: "iOS Simulator,OS=17.5,name=iPhone 15 Pro"
          - os: macos-14
            xcode: 15.4
            platform: "macOS"
          - os: macos-14
            xcode: 15.4
            platform: "macOS,variant=Mac Catalyst"

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Xcode Version
        run: xcodebuild -version

      - name: Show SDKs
        run: xcodebuild -showsdks

      - name: Show Destinations
        run: xcodebuild -scheme LiveKitComponents -showdestinations

      - name: Run Tests on ${{ matrix.platform }}
        run: xcodebuild test -scheme LiveKitComponents -destination 'platform=${{ matrix.platform }}' -parallel-testing-enabled YES
